version: '3.1'
services:
  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mostafa
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgresDB 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./database_entry:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - "3006:80"
